### ISSUE TITLE
Building mongo v7.x fails on Debian 12/Bookworm

### ISSUE THREAD

**Issue by JedMeister** [GermanAizek/mongodb-without-avx#10]
Hi, thanks for providing this and apologies for another "doesn't work" issue. I've looked through the others and nothing seems the same as what I'm hitting, so I'll try to share as much info as possible.

It's possible that lack of resources (RAM? free space on the root volume should be enough) is the issue, but the error doesn't explicitly note that so I haven't tried anything there. Here is the command I used to build (full setup noted below):

```
python3 buildscripts/scons.py -j 2 --linker=gold --disable-warnings-as-errors install-mongod | tee build.log
```
(I added the `--linker=gold` switch after getting a previous fatal error which suggested adding that - it goes for much longer using that switch).

And here are the last few lines where it fails (I'll also attach the `build.log` file):

```
src/mongo/util/aligned.h:205:85: warning: use of 'std::hardware_destructive_interference_size' [-Winterference-size]
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
scons: *** [build/opt/mongo/db/s/cluster_count_cmd_d.o] Error 1
scons: building terminated because of errors.
build/opt/mongo/db/s/cluster_count_cmd_d.o failed: Error 1
```

System: Debian 12/Bookworm
Platform/Specs: KVM VM with 2 vCPUs, 2GB RAM
Storage: 21G used of 27G root volume (84% usage)

mongodb-without-avx: `044b1c6 (HEAD -> main, origin/main, origin/HEAD) Merge pull request #5 from Caprico85/fix-patch`
mongo: `006518628b5 (HEAD) SERVER-73985 Database init code should not create a yieldable CollectionPtr`

Here are the commands that I used to set up:
```
apt install -y python-dev-is-python3 libssl-dev build-essential python3-pip python3-venv libcurl4-openssl-dev liblzma-dev
git clone --recurse-submodules https://github.com/GermanAizek/mongodb-without-avx.git

cd mongodb-without-avx/mongo
python3 -m venv python3-venv
source python3-venv/bin/activate
pip install -r etc/pip/compile-requirements.txt
# build_metrics tool deps - not sure if these are really needed?
pip install memory_profiler puremagic networkx cxxfilt
patch -p1 SConstruct < ../o2_patch.diff
python3 buildscripts/scons.py -j 2 --linker=gold --disable-warnings-as-errors install-mongod | tee build.log
```

Complete log attached: [build.log](https://github.com/GermanAizek/mongodb-without-avx/files/13494741/build.log)

**Comment by GermanAizek** [comment]
@JedMeister, to build latest version MongoDB requires at least 12 GB RAM. I myself am surprised by such requirements, an to try change another linker or compiler.

![image](https://github.com/GermanAizek/mongodb-without-avx/assets/21138600/b8cb9287-9895-4fd0-b360-e020f8073906)

**Comment by JedMeister** [comment]
Thanks for your quick reply @GermanAizek - Wow! Ok, that certainly explains it then...

I'll try again with more RAM and fingers crossed that should do it. I'll try to remember to post back regardless.

**Comment by JedMeister** [comment]
I've given my new VM 12GB RAM. Hopefully that will be enough - it's near all I have spare ATM.

FWIW, it's been building for a bit over an hour now and RAM usage is mostly sitting between 5GB -> 7GB - peaked at ~8GB at the 30 minute mark.
