### ISSUE TITLE
compiled successfully, but 

### ISSUE THREAD

**Issue by turb0t72** [GermanAizek/mongodb-without-avx#4]
Managed to get this to compile after resolving all the dependencies, its in the READ.md
It took about a  day to compile on a VM of ubuntu 22, with 4 cores AMD EPYC 7742, and 8G RAM
But the size is HUGE
ls -lh mongod
-rwxrwxr-x 2 ianh ianh 3.9G May 31 07:29 mongod

**Comment by GermanAizek** [comment]
@turb0t72,
Thank you so much, you correctly noticed the problem, by default, if you build yourself from source code, it applies the optimization flag -O2, which is not most optimized and takes up a lot of space, I can make different patches that optimize the size binary with flag -Os, and another patch maximum optimization speed with flag -O3

**Comment by GermanAizek** [comment]
@turb0t72,
Also, do not forget that you have a Zen 2 architecture, and you can optimize mongodb more for it, I will now make a convenient choice of different patches for different processors and different optimization flags.

**Comment by GermanAizek** [comment]
@turb0t72, I fixed patches, they generate a more optimized binary, in your case server solution, it is better to take `o3_patch.diff`, if the size of the binary is important, then `os_patch.diff`

Commit here: f74bf316c7e37ae416650cc1dc7680d5ac22b82e

**Comment by GermanAizek** [comment]
@turb0t72, my question is, how many "-j" have you set? Anyway, this is the number of threads in your processor, the more, the faster compilation is performed, but there should not be a value greater than the physical count threads ( or cores if CPU dont have Intel HT and AMD SMT "old cpu's" )

**Comment by turb0t72** [comment]
@GermanAizek 
I had set -j1 and tried no other value.
I originally tried to build on VM ubuntu22 with 4G and 2CPU L5420
And this failed with oom-killer issues, so i spun up a VM at work with more memory , more CPUs and more disk. Initially it had 8G RAM, but now it has 16G
I had intended to re-package into a docker container, but I also saw that you have a Docker file to build such a container.  This also builds ok, but the container ends about 10 seconds after starting.

The AMD system I was building it on is not the target system I will run this on. L5420 does support AVX, but not carry this instruction through in virtualisation with VMware or Proxmox

**Comment by turb0t72** [comment]
I have built mongo again without avx support, and have put it in a docker container
When I run the original mongo docker and the new mongo docker without avx , both side by side on the same  AMD EPYC 7742 vm platform, both work and continue running.
When i run the docker container for mongo without avx on my other vm platform which does not have avx via qemu, it aborts after about 15 seconds.

**Comment by turb0t72** [comment]
Forget my last comment.
It failed because I gave it mongo v4.0 data.
Having deleted the data and run it again, it works well.
Thank you for providing details on how to compile mongo without AVX.
